apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tasks-deft-collector
spec:
  schedule: "20 */1 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wfms-tasks-enrich-deft
              image: atlasanalyticsservice/wfms:latest
              command: ["Tasks/Enrich/DEFT/run.sh"]
              env:
                - name: JOB_ORACLE_USER
                  valueFrom:
                    secretKeyRef:
                      name: oracle-secret
                      key: job_oracle_user
                - name: JOB_ORACLE_PASS
                  valueFrom:
                    secretKeyRef:
                      name: oracle-secret
                      key: job_oracle_pass
                - name: JOB_ORACLE_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: oracle-secret
                      key: job_oracle_connection_string
          restartPolicy: Never
